version: '3'

services:

  dynamodb:
    image: amazon/dynamodb-local
    hostname: dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
  
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DYNAMO_DB_ENDPOINT=http://host.docker.internal:8000
      - AWS_ACCESS_KEY_ID=some-key
      - AWS_ACCESS_KEY_SECRET=some-secret
    depends_on:
      - dynamodb



  