UNIT_TEST_DIR=$(shell go list ./... | grep -v /server | grep -v /cmd )

run: test
	@docker-compose build
	@docker-compose up


test:
	go get gotest.tools/gotestsum
	gotestsum --jsonfile report.json -- -coverprofile=coverage.out -race -v ${UNIT_TEST_DIR}
	go mod tidy
